global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # 1. Konfigurasi untuk memantau Prometheus itu sendiri
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # 2. Konfigurasi untuk memantau Model ML Anda (di port 8000)
  - job_name: 'ml_model'
    static_configs:
      - targets: ['localhost:8000']